stages:
  - build
  - deploy

build_job:
  stage: build
  script:
    - docker build -t registry.gitlab.com/yourusername/smart-feedback-app .
    - docker login registry.gitlab.com -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker push registry.gitlab.com/yourusername/smart-feedback-app

deploy_job:
  stage: deploy
  script:
    - ssh ec2-user@YOUR_EC2_PUBLIC_IP "docker pull registry.gitlab.com/yourusername/smart-feedback-app && \
      docker stop feedback_container || true && \
      docker rm feedback_container || true && \
      docker run -d --name feedback_container -p 80:8000 registry.gitlab.com/yourusername/smart-feedback-app"
